# 运行:docker-compose up -d

services:
  mysql:
    image: mysql:8.4  # 使用 MySQL 8.x 版本
    environment:
      MYSQL_ROOT_PASSWORD: 'root_123456'  # 设置 MySQL root 用户的密码
      MYSQL_DATABASE: 'serve_api_db'                # 可选，自动创建一个数据库
      MYSQL_USER: 'user'                  # 可选，创建一个用户
      MYSQL_PASSWORD: 'user_123456'              # 可选，设置该用户的密码
    ports:
      - '3306:3306'  # 将容器的 3306 端口映射到宿主机的 3306 端口上
    volumes:
      - ./docker_data/mysql:/var/lib/mysql  # 数据持久化存储
    command: 'mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci'  # 命令
    restart: always  # 设置服务总是重新启动
